trigger:
- master

pool:
  vmImage: 'windows-latest'

parameters:
  - name: solutionPath
    type: string
    default: 'G9SignalRSuperNetCore/G9SignalRSuperNetCore.sln'
  - name: testProjects
    type: string
    default: 'null' # Leave empty if no test projects are defined
  - name: nugetPackages
    type: object
    default:
      - 'G9SignalRSuperNetCore.Client/bin/Release/*.nupkg'
      - 'G9SignalRSuperNetCore.Server/bin/Release/*.nupkg'
  - name: repositoryName
    type: string
    default: 'G9SignalRSuperNetCore' # Default to the same as the project name

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Install NuGet tool
- task: NuGetToolInstaller@1

# Restore NuGet packages
- task: NuGetCommand@2
  inputs:
    restoreSolution: '${{ parameters.solutionPath }}'

- task: VSBuild@1
  displayName: Build Client Resource Generator
  inputs:
    solution: 'G9SignalRSuperNetCore/G9SignalRSuperNetCore.Server.ClientResourceGenerator/G9SignalRSuperNetCore.Server.ClientResourceGenerator.csproj'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:TargetFramework=netstandard2.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Build the solution
- task: VSBuild@1
  inputs:
    solution: '${{ parameters.solutionPath }}'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:ContinuousIntegrationBuild=true /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Set runtime variable for tests
- script: |
    if [ "${{ parameters.testProjects }}" != "null" ]; then
      echo "##vso[task.setvariable variable=runTests]true"
    else
      echo "##vso[task.setvariable variable=runTests]false"
    fi
  displayName: "Evaluate Test Projects"

# Run tests if applicable
- ${{ if eq(variables.runTests, 'true') }}:
  - task: VSTest@2
    displayName: Run Unit Tests
    inputs:
      testSelector: testAssemblies
      testAssemblyVer2: '${{ parameters.testProjects }}'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

# Publish NuGet packages
- ${{ each packagePath in parameters.nugetPackages }}:
  - task: DotNetCoreCLI@2
    displayName: "Publish NuGet Package - $(packagePath)"
    inputs:
      command: custom
      custom: nuget
      arguments: >
        push $(Pipeline.Workspace)/$(packagePath)
        -s https://api.nuget.org/v3/index.json
        -k $(NuGetApiKey) 
        --skip-duplicate

# Sync Azure DevOps repo with GitHub repo
- task: PowerShell@2
  displayName: "Sync Azure DevOps repo with GitHub repo"
  inputs:
    targetType: 'inline'
    script: |
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - -'
      Write-Host ' Reflect Azure DevOps repo changes to GitHub repo'
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - - '
      
      $repoName = "${{ parameters.repositoryName }}"
      $stageDir = "$(Build.SourcesDirectory)"
      $githubDir = "$stageDir/gitHub"
      $destination = "$githubDir/$repoName.git"

      # Please provide your GitHub username
      $alias = "ImanKari:" + "$(Github.PAT)"

      # Source and destination repository URLs
      $sourceURL = "https://$(AzureDevOps.PAT)@dev.azure.com/YourOrg/_git/$repoName"
      $destURL = "https://$alias@github.com/ImanKari/$repoName.git"

      # Ensure the directory structure is clean
      if (Test-Path -Path $githubDir) {
        Remove-Item -Path $githubDir -Recurse -Force
      }

      New-Item -ItemType Directory -Path $githubDir | Out-Null
      Set-Location $githubDir

      # Clone the repository
      git clone --mirror $sourceURL
      Set-Location $destination

      # Sync changes
      git remote add --mirror=fetch secondary $destURL
      git fetch origin
      git push secondary --all
      git push secondary --tags

      Write-Host '**Azure DevOps repo synced with GitHub repo**'

      # Cleanup
      Set-Location $stageDir
      if (Test-Path -Path $githubDir) {
        Remove-Item -Path $githubDir -Recurse -Force
      }
