using System.Linq;
using System.Text;

namespace G9SignalRSuperNetCore.SourceGenerator;

/// <summary>
///     Renders a <see cref="HubModel"/> into a single C# compilation unit with no runtime
///     reflection. Every server method becomes a typed <c>HubConnection.InvokeCoreAsync</c>
///     or <c>SendCoreAsync</c> call, every listener becomes a typed <c>HubConnection.On&lt;...&gt;</c>
///     binding.
/// </summary>
internal static class G9Emitter
{
    public static string Emit(HubModel hub)
    {
        var sb = new StringBuilder(8 * 1024);

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   G9SignalRSuperNetCore source generator");
        sb.AppendLine("//   Hub: " + hub.FullyQualifiedClassName);
        sb.AppendLine("//   AOT- and trim-safe; no Reflection.Emit; no MethodInfo.Invoke on the hot path.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using G9SignalRSuperNetCore.Client;");
        sb.AppendLine("using Microsoft.AspNetCore.Http.Connections.Client;");
        sb.AppendLine("using Microsoft.AspNetCore.SignalR.Client;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(hub.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(hub.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        EmitMethodsInterface(sb, hub);
        sb.AppendLine();
        EmitListenersInterface(sb, hub);
        sb.AppendLine();
        EmitClientClass(sb, hub);
        sb.AppendLine();
        EmitServerProxy(sb, hub);

        return sb.ToString();
    }

    private static string SuffixForKind(HubKind kind) =>
        kind is HubKind.JwtAuth or HubKind.SessionAndJwtAuth ? "WithJWTAuth" : string.Empty;

    private static void EmitMethodsInterface(StringBuilder sb, HubModel hub)
    {
        var ifaceName = $"I{hub.ClassName}Methods{SuffixForKind(hub.Kind)}";

        sb.AppendLine("/// <summary>");
        sb.Append("///   Strongly-typed surface of server-side methods exposed by hub <c>")
          .Append(hub.ClassName).AppendLine("</c>.");
        sb.AppendLine("///   Implemented by the auto-generated proxy class which routes each call");
        sb.AppendLine("///   through <see cref=\"HubConnection\"/> with no runtime reflection.");
        sb.AppendLine("/// </summary>");
        sb.Append("public interface ").Append(ifaceName).AppendLine();
        sb.AppendLine("{");

        foreach (var method in hub.ServerMethods)
        {
            EmitXmlDoc(sb, method.XmlDocCommentXml, indent: "    ");
            sb.Append("    ").Append(method.ReturnTypeFqName).Append(' ')
              .Append(method.Name).Append('(')
              .Append(string.Join(", ", method.Parameters.Select(p => $"{p.TypeFqName} {p.Name}")))
              .AppendLine(");");
        }

        sb.AppendLine("}");
    }

    private static void EmitListenersInterface(StringBuilder sb, HubModel hub)
    {
        var ifaceName = $"I{hub.ClassName}Listeners{SuffixForKind(hub.Kind)}";

        sb.AppendLine("/// <summary>");
        sb.Append("///   Strongly-typed surface of client-side callbacks the server can invoke for hub <c>")
          .Append(hub.ClassName).AppendLine("</c>.");
        sb.AppendLine("///   Implemented by the auto-generated client class with overridable defaults.");
        sb.AppendLine("/// </summary>");
        sb.Append("public interface ").Append(ifaceName).AppendLine();
        sb.AppendLine("{");

        foreach (var method in hub.ListenerMethods)
        {
            EmitXmlDoc(sb, method.XmlDocCommentXml, indent: "    ");
            sb.Append("    ").Append(method.ReturnTypeFqName).Append(' ')
              .Append(method.Name).Append('(')
              .Append(string.Join(", ", method.Parameters.Select(p => $"{p.TypeFqName} {p.Name}")))
              .AppendLine(");");
        }

        sb.AppendLine("}");
    }

    private static void EmitClientClass(StringBuilder sb, HubModel hub)
    {
        var suffix = SuffixForKind(hub.Kind);
        var clientName = $"{hub.ClassName}Client{suffix}";
        var methodsIface = $"I{hub.ClassName}Methods{suffix}";
        var listenersIface = $"I{hub.ClassName}Listeners{suffix}";
        var isJwt = hub.Kind is HubKind.JwtAuth or HubKind.SessionAndJwtAuth;

        var baseClass = isJwt
            ? $"global::G9SignalRSuperNetCore.Client.G9SignalRSuperNetCoreClientWithJWTAuth<{clientName}, {methodsIface}, {listenersIface}>"
            : $"global::G9SignalRSuperNetCore.Client.G9SignalRSuperNetCoreClient<{clientName}, {methodsIface}, {listenersIface}>";

        sb.AppendLine("/// <summary>");
        sb.Append("///   Strongly-typed, AOT-safe SignalR client for hub <c>")
          .Append(hub.ClassName).AppendLine("</c>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("///   <para>");
        sb.AppendLine("///     This class is generated from the hub definition by the G9SignalRSuperNetCore source generator.");
        sb.Append("///     It is a partial class so you can extend it with custom listener overrides in your own code:")
          .AppendLine();
        sb.AppendLine("///     just declare another <c>partial class " + clientName + "</c> in the same project");
        sb.AppendLine("///     and override the listener methods you care about.");
        sb.AppendLine("///   </para>");
        sb.AppendLine("///   <para>");
        sb.AppendLine("///     The generated proxy uses only <see cref=\"HubConnection.InvokeCoreAsync\"/> and");
        sb.AppendLine("///     <see cref=\"HubConnection.SendCoreAsync\"/>, with no runtime reflection or proxy generation.");
        sb.AppendLine("///   </para>");
        sb.AppendLine("/// </remarks>");
        sb.Append("public partial class ").Append(clientName).AppendLine();
        sb.Append("    : ").Append(baseClass).Append(", ").Append(listenersIface).AppendLine();
        sb.AppendLine("{");
        sb.Append("    private ").Append(hub.ClassName).Append("ServerProxy").Append(suffix)
          .AppendLine("? _serverProxy;");
        sb.AppendLine();

        if (isJwt)
        {
            sb.Append("    /// <summary>Initializes a new <see cref=\"").Append(clientName).AppendLine("\"/>.</summary>");
            sb.Append("    public ").Append(clientName).AppendLine("(");
            sb.AppendLine("        string serverUrl,");
            sb.AppendLine("        string? jwToken = null,");
            sb.AppendLine("        Func<IHubConnectionBuilder, IHubConnectionBuilder>? customConfigureBuilder = null,");
            sb.AppendLine("        Func<IHubConnectionBuilder, IHubConnectionBuilder>? customConfigureBuilderForAuthServer = null,");
            sb.AppendLine("        Action<HttpConnectionOptions>? configureHttpConnection = null,");
            sb.AppendLine("        Action<HttpConnectionOptions>? configureHttpConnectionForAuthServer = null)");
            sb.AppendLine("        : base(");
            sb.Append("            $\"{serverUrl}").Append(hub.RoutePattern).AppendLine("\",");
            sb.Append("            $\"{serverUrl}").Append(hub.AuthRoutePattern).AppendLine("\",");
            sb.AppendLine("            jwToken,");
            sb.AppendLine("            customConfigureBuilder,");
            sb.AppendLine("            customConfigureBuilderForAuthServer,");
            sb.AppendLine("            configureHttpConnection,");
            sb.AppendLine("            configureHttpConnectionForAuthServer)");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
        }
        else
        {
            sb.Append("    /// <summary>Initializes a new <see cref=\"").Append(clientName).AppendLine("\"/>.</summary>");
            sb.Append("    public ").Append(clientName).AppendLine("(");
            sb.AppendLine("        string serverUrl,");
            sb.AppendLine("        Func<IHubConnectionBuilder, IHubConnectionBuilder>? customConfigureBuilder = null,");
            sb.AppendLine("        Action<HttpConnectionOptions>? configureHttpConnection = null)");
            sb.AppendLine("        : base(");
            sb.Append("            $\"{serverUrl}").Append(hub.RoutePattern).AppendLine("\",");
            sb.AppendLine("            customConfigureBuilder,");
            sb.AppendLine("            configureHttpConnection)");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
        }
        sb.AppendLine();

        // Server proxy property
        sb.AppendLine("    /// <inheritdoc />");
        sb.Append("    public override ").Append(methodsIface).AppendLine(" Server =>");
        sb.Append("        _serverProxy ??= new ").Append(hub.ClassName).Append("ServerProxy").Append(suffix)
          .AppendLine("(this);");
        sb.AppendLine();

        // Listener registration
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    protected override void RegisterListenerMethods()");
        sb.AppendLine("    {");
        foreach (var listener in hub.ListenerMethods)
        {
            EmitListenerRegistration(sb, listener);
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // Default listener implementations (virtual so consumers can override in a partial class)
        foreach (var listener in hub.ListenerMethods)
        {
            EmitDefaultListener(sb, listener);
        }

        sb.AppendLine("}");
    }

    private static void EmitListenerRegistration(StringBuilder sb, ListenerMethodModel listener)
    {
        sb.Append("        Connection.On");

        if (listener.Parameters.Count > 0)
        {
            sb.Append('<')
              .Append(string.Join(", ", listener.Parameters.Select(p => p.TypeFqName)))
              .Append('>');
        }

        sb.Append("(\"").Append(listener.Name).Append("\", ");

        if (listener.Parameters.Count == 0)
        {
            sb.Append("() => InvokeListener_").Append(listener.Name).Append("()");
        }
        else
        {
            sb.Append('(');
            sb.Append(string.Join(", ", listener.Parameters.Select(p => p.Name)));
            sb.Append(") => InvokeListener_").Append(listener.Name).Append('(');
            sb.Append(string.Join(", ", listener.Parameters.Select(p => p.Name)));
            sb.Append(')');
        }

        sb.AppendLine(");");
    }

    private static void EmitDefaultListener(StringBuilder sb, ListenerMethodModel listener)
    {
        var paramList = string.Join(", ", listener.Parameters.Select(p => $"{p.TypeFqName} {p.Name}"));
        var argList = string.Join(", ", listener.Parameters.Select(p => p.Name));

        // Public virtual implementation that consumers can override.
        EmitXmlDoc(sb, listener.XmlDocCommentXml, indent: "    ");
        sb.Append("    public virtual ").Append(listener.ReturnTypeFqName).Append(' ')
          .Append(listener.Name).Append('(').Append(paramList).Append(") => ");
        sb.AppendLine(listener.ReturnKind == ListenerReturnKind.ValueTask
            ? "global::System.Threading.Tasks.ValueTask.CompletedTask;"
            : "global::System.Threading.Tasks.Task.CompletedTask;");

        // Private dispatch shim that always returns a Task (HubConnection.On wants Task).
        sb.Append("    private global::System.Threading.Tasks.Task InvokeListener_").Append(listener.Name)
          .Append('(').Append(paramList).AppendLine(")");
        sb.AppendLine("    {");
        if (listener.ReturnKind == ListenerReturnKind.ValueTask)
        {
            sb.Append("        var vt = ").Append(listener.Name).Append('(').Append(argList).AppendLine(");");
            sb.AppendLine("        return vt.IsCompletedSuccessfully ? global::System.Threading.Tasks.Task.CompletedTask : vt.AsTask();");
        }
        else
        {
            sb.Append("        return ").Append(listener.Name).Append('(').Append(argList).AppendLine(");");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitServerProxy(StringBuilder sb, HubModel hub)
    {
        var suffix = SuffixForKind(hub.Kind);
        var clientName = $"{hub.ClassName}Client{suffix}";
        var proxyName = $"{hub.ClassName}ServerProxy{suffix}";
        var methodsIface = $"I{hub.ClassName}Methods{suffix}";

        sb.AppendLine("/// <summary>");
        sb.Append("///   Internal proxy that turns calls on <see cref=\"").Append(methodsIface)
          .AppendLine("\"/> into");
        sb.AppendLine("///   <see cref=\"HubConnection.InvokeCoreAsync\"/> or <see cref=\"HubConnection.SendCoreAsync\"/>");
        sb.AppendLine("///   without any runtime reflection.");
        sb.AppendLine("/// </summary>");
        sb.Append("internal sealed class ").Append(proxyName).Append(" : ").Append(methodsIface).AppendLine();
        sb.AppendLine("{");
        sb.Append("    private readonly ").Append(clientName).AppendLine(" _owner;");
        sb.Append("    public ").Append(proxyName).Append('(').Append(clientName).AppendLine(" owner) => _owner = owner;");
        sb.AppendLine();

        foreach (var m in hub.ServerMethods)
        {
            EmitServerProxyMethod(sb, m);
        }

        sb.AppendLine("}");
    }

    private static void EmitServerProxyMethod(StringBuilder sb, MethodModel method)
    {
        var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.TypeFqName} {p.Name}"));
        var nonCancelArgs = method.Parameters.Where(p => !p.IsCancellationToken).ToArray();
        var cancellationArg = method.Parameters.FirstOrDefault(p => p.IsCancellationToken);
        var ctExpr = cancellationArg is null ? "global::System.Threading.CancellationToken.None" : cancellationArg.Name;

        var argArray = nonCancelArgs.Length == 0
            ? "global::System.Array.Empty<object?>()"
            : "new object?[] { " + string.Join(", ", nonCancelArgs.Select(p => p.Name)) + " }";

        EmitXmlDoc(sb, method.XmlDocCommentXml, indent: "    ");

        switch (method.ReturnKind)
        {
            case MethodReturnKind.Task:
                sb.Append("    public ").Append(method.ReturnTypeFqName).Append(' ').Append(method.Name)
                  .Append('(').Append(paramList).AppendLine(")");
                sb.Append("        => _owner.Connection.SendCoreAsync(\"").Append(method.Name)
                  .Append("\", ").Append(argArray).Append(", ").Append(ctExpr).AppendLine(");");
                break;

            case MethodReturnKind.TaskOfT:
                sb.Append("    public ").Append(method.ReturnTypeFqName).Append(' ').Append(method.Name)
                  .Append('(').Append(paramList).AppendLine(")");
                sb.Append("        => _owner.Connection.InvokeCoreAsync<").Append(method.UnwrappedTypeFqName)
                  .Append(">(\"").Append(method.Name).Append("\", ").Append(argArray)
                  .Append(", ").Append(ctExpr).AppendLine(");");
                break;

            case MethodReturnKind.ValueTask:
                sb.Append("    public ").Append(method.ReturnTypeFqName).Append(' ').Append(method.Name)
                  .Append('(').Append(paramList).AppendLine(")");
                sb.Append("        => new global::System.Threading.Tasks.ValueTask(_owner.Connection.SendCoreAsync(\"")
                  .Append(method.Name).Append("\", ").Append(argArray).Append(", ").Append(ctExpr).AppendLine("));");
                break;

            case MethodReturnKind.ValueTaskOfT:
                sb.Append("    public ").Append(method.ReturnTypeFqName).Append(' ').Append(method.Name)
                  .Append('(').Append(paramList).AppendLine(")");
                sb.Append("        => new global::System.Threading.Tasks.ValueTask<").Append(method.UnwrappedTypeFqName)
                  .Append(">(_owner.Connection.InvokeCoreAsync<").Append(method.UnwrappedTypeFqName)
                  .Append(">(\"").Append(method.Name).Append("\", ").Append(argArray)
                  .Append(", ").Append(ctExpr).AppendLine("));");
                break;

            case MethodReturnKind.AsyncEnumerableOfT:
                sb.Append("    public ").Append(method.ReturnTypeFqName).Append(' ').Append(method.Name)
                  .Append('(').Append(paramList).AppendLine(")");
                sb.Append("        => _owner.Connection.StreamAsyncCore<").Append(method.UnwrappedTypeFqName)
                  .Append(">(\"").Append(method.Name).Append("\", ").Append(argArray)
                  .Append(", ").Append(ctExpr).AppendLine(");");
                break;
        }

        sb.AppendLine();
    }

    /// <summary>
    ///     Emits the symbol's XML documentation comment as <c>///</c>-prefixed lines so the generated
    ///     proxy and listener members carry the same IntelliSense your hub source did.
    /// </summary>
    private static void EmitXmlDoc(StringBuilder sb, string? rawXml, string indent)
    {
        if (string.IsNullOrWhiteSpace(rawXml)) return;

        // Roslyn returns the doc wrapped in <member name="...">...</member>. Strip the wrapper.
        var inner = ExtractInner(rawXml!);
        if (string.IsNullOrWhiteSpace(inner)) return;

        foreach (var line in inner.Split(new[] { '\r', '\n' }, System.StringSplitOptions.RemoveEmptyEntries))
        {
            var trimmed = line.Trim();
            if (trimmed.Length == 0) continue;
            sb.Append(indent).Append("/// ").AppendLine(trimmed);
        }
    }

    private static string ExtractInner(string xml)
    {
        var openTagEnd = xml.IndexOf('>');
        var closeTagStart = xml.LastIndexOf("</member>", System.StringComparison.Ordinal);
        if (openTagEnd < 0 || closeTagStart < 0 || closeTagStart <= openTagEnd) return xml;
        return xml.Substring(openTagEnd + 1, closeTagStart - openTagEnd - 1);
    }
}
