// <auto-generated/>
#nullable enable
// Hand-mirrored sample of what the build-time generator produces.
// In a real consumer project you would copy the latest content of
// WebServer/GeneratedClientHelpers.txt into a .cs file in the client project.
// AOT- and trim-safe; uses no runtime reflection or proxy generation.

using System;
using System.Threading;
using System.Threading.Tasks;
using G9SignalRSuperNetCore.Client;
using G9SignalRSuperNetCore.ConsoleClient;
using Microsoft.AspNetCore.Http.Connections.Client;
using Microsoft.AspNetCore.SignalR.Client;

/* ---------------------------------------------------------------
 *   Auto-generated AOT-safe client helper for hub 'CustomHubWithJWTAuthAndSession'
 * --------------------------------------------------------------- */

/// <summary>Server methods callable from the client.</summary>
public interface ICustomHubWithJWTAuthAndSessionMethodsWithJWTAuth
{
    Task Login(string userName, string password);
    Task Replay(string message);
    Task TestResult(string result1, string result2);
    Task<List<string>> GetList();
    Task<DtSimpleResultWithExtraData> GetDataType();
}

/// <summary>Client-side callbacks the server can invoke.</summary>
public interface ICustomHubWithJWTAuthAndSessionListenersWithJWTAuth
{
    Task LoginResult(bool accepted);
    Task Replay(string message);
    Task TestResult(string result1, string result2);
}

/// <summary>
/// Strongly-typed, AOT-safe client for the SignalR hub 'CustomHubWithJWTAuthAndSession'.
/// </summary>
public partial class CustomHubWithJWTAuthAndSessionClientWithJWTAuth :
    G9SignalRSuperNetCoreClientWithJWTAuth<
        CustomHubWithJWTAuthAndSessionClientWithJWTAuth,
        ICustomHubWithJWTAuthAndSessionMethodsWithJWTAuth,
        ICustomHubWithJWTAuthAndSessionListenersWithJWTAuth>,
    ICustomHubWithJWTAuthAndSessionListenersWithJWTAuth
{
    private CustomHubWithJWTAuthAndSessionServerProxy? _serverProxy;

    public CustomHubWithJWTAuthAndSessionClientWithJWTAuth(
        string serverUrl,
        string? jwToken = null,
        Func<IHubConnectionBuilder, IHubConnectionBuilder>? customConfigureBuilder = null,
        Func<IHubConnectionBuilder, IHubConnectionBuilder>? customConfigureBuilderForAuthServer = null,
        Action<HttpConnectionOptions>? configureHttpConnection = null,
        Action<HttpConnectionOptions>? configureHttpConnectionForAuthServer = null)
        : base(
            $"{serverUrl}/SecureHub",
            $"{serverUrl}/AuthHub",
            jwToken,
            customConfigureBuilder,
            customConfigureBuilderForAuthServer,
            configureHttpConnection,
            configureHttpConnectionForAuthServer)
    {
    }

    public override ICustomHubWithJWTAuthAndSessionMethodsWithJWTAuth Server =>
        _serverProxy ??= new CustomHubWithJWTAuthAndSessionServerProxy(this);

    protected override void RegisterListenerMethods()
    {
        Connection.On<bool>(nameof(LoginResult), accepted => LoginResult(accepted));
        Connection.On<string>(nameof(Replay), msg => Replay(msg));
        Connection.On<string, string>(nameof(TestResult), (a, b) => TestResult(a, b));
    }

    public virtual Task LoginResult(bool accepted)
    {
        Console.WriteLine($"LoginResult: {accepted}");
        return Task.CompletedTask;
    }

    public virtual Task Replay(string message)
    {
        Console.WriteLine($"Replay: {message}");
        return Task.CompletedTask;
    }

    public virtual Task TestResult(string result1, string result2)
    {
        Console.WriteLine($"TestResult: {result1} | {result2}");
        return Task.CompletedTask;
    }
}

internal sealed class CustomHubWithJWTAuthAndSessionServerProxy : ICustomHubWithJWTAuthAndSessionMethodsWithJWTAuth
{
    private readonly CustomHubWithJWTAuthAndSessionClientWithJWTAuth _owner;

    public CustomHubWithJWTAuthAndSessionServerProxy(CustomHubWithJWTAuthAndSessionClientWithJWTAuth owner)
    {
        _owner = owner;
    }

    public Task Login(string userName, string password)
        => _owner.Connection.SendCoreAsync(nameof(Login), new object?[] { userName, password });

    public Task Replay(string message)
        => _owner.Connection.SendCoreAsync(nameof(Replay), new object?[] { message });

    public Task TestResult(string result1, string result2)
        => _owner.Connection.SendCoreAsync(nameof(TestResult), new object?[] { result1, result2 });

    public Task<List<string>> GetList()
        => _owner.Connection.InvokeCoreAsync<List<string>>(nameof(GetList), Array.Empty<object?>());

    public Task<DtSimpleResultWithExtraData> GetDataType()
        => _owner.Connection.InvokeCoreAsync<DtSimpleResultWithExtraData>(nameof(GetDataType), Array.Empty<object?>());
}
