using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

/// <summary>
///     MSBuild task that generates AOT-safe SignalR client-side helper code for
///     G9SignalRSuperNetCore hubs.
/// </summary>
/// <remarks>
///     For every class that derives from <c>G9AHubBase</c>, this task emits a strongly-typed
///     methods interface, a strongly-typed listeners interface, and a client class that
///     uses <c>HubConnection.InvokeCoreAsync</c> / <c>SendCoreAsync</c> directly.
///     No runtime reflection or proxy generation is required, making the generated code
///     fully AOT- and trim-safe.
/// </remarks>
// ReSharper disable once UnusedMember.Global
// ReSharper disable once CheckNamespace
public class G9HubClientGeneratorTask : Task
{
    /// <summary>The directory containing the source files to process.</summary>
    [Required]
    public string InputDirectory { get; set; } = string.Empty;

    /// <summary>The output file path for the generated client helper code.</summary>
    [Required]
    public string OutputFile { get; set; } = string.Empty;

    /// <inheritdoc />
    public override bool Execute()
    {
        try
        {
            var generated = new StringBuilder();
            generated.AppendLine("// <auto-generated/>");
            generated.AppendLine("// G9SignalRSuperNetCore — typed client helpers");
            generated.AppendLine("// AOT- and trim-safe; uses no runtime reflection or proxy generation.");
            generated.AppendLine();
            generated.AppendLine("using System;");
            generated.AppendLine("using System.Threading;");
            generated.AppendLine("using System.Threading.Tasks;");
            generated.AppendLine("using G9SignalRSuperNetCore.Client;");
            generated.AppendLine("using Microsoft.AspNetCore.Http.Connections.Client;");
            generated.AppendLine("using Microsoft.AspNetCore.SignalR.Client;");
            generated.AppendLine();

            var hubFiles = Directory.GetFiles(InputDirectory, "*.cs", SearchOption.AllDirectories)
                .Where(p => p.IndexOf("\\obj\\", StringComparison.OrdinalIgnoreCase) < 0
                            && p.IndexOf("\\bin\\", StringComparison.OrdinalIgnoreCase) < 0
                            && p.IndexOf("/obj/", StringComparison.OrdinalIgnoreCase) < 0
                            && p.IndexOf("/bin/", StringComparison.OrdinalIgnoreCase) < 0);

            // Cache the parsed syntax trees once so we don't reparse for every interface lookup.
            var parsedTrees = hubFiles.Select(p => (Path: p, Tree: CSharpSyntaxTree.ParseText(File.ReadAllText(p))))
                .ToList();

            foreach (var (filePath, tree) in parsedTrees)
            {
                var root = tree.GetRoot();
                var hubClasses = root.DescendantNodes()
                    .OfType<ClassDeclarationSyntax>()
                    .Where(cls => cls.BaseList != null && cls.BaseList.Types
                        .Any(bt => bt.ToString().Contains("G9AHubBase")));

                foreach (var hubClass in hubClasses)
                {
                    var className = hubClass.Identifier.Text;
                    var clientInterface = ExtractClientInterface(hubClass);
                    var serverMethods = ExtractAnnotatedMethods(hubClass);
                    var code = GenerateCode(className, clientInterface, serverMethods, hubClass, parsedTrees);
                    generated.AppendLine(code);
                }
            }

            File.WriteAllText(OutputFile, generated.ToString());
            Log.LogMessage(MessageImportance.High, $"Generated client helper file at: {OutputFile}");
            return true;
        }
        catch (Exception ex)
        {
            Log.LogErrorFromException(ex);
            return false;
        }
        finally
        {
            for (var i = 0; i < GC.MaxGeneration; i++)
            {
                GC.Collect(i, GCCollectionMode.Forced);
                GC.WaitForPendingFinalizers();
            }
        }
    }

    private static string ExtractClientInterface(ClassDeclarationSyntax cls)
    {
        if (cls.BaseList == null) return "UnknownInterface";
        var baseType = cls.BaseList.Types.First(bt => bt.ToString().Contains("G9AHubBase"));
        var generics = baseType.ToString()
            .Split('<', '>', ',')
            .Skip(1)
            .Where(a => !string.IsNullOrWhiteSpace(a))
            .Select(a => a.Trim())
            .ToList();
        return generics.ElementAtOrDefault(1) ?? "UnknownInterface";
    }

    private static List<MethodDeclarationSyntax> ExtractAnnotatedMethods(ClassDeclarationSyntax cls)
    {
        var excluded = new HashSet<string>(StringComparer.Ordinal)
        {
            "RoutePattern", "ValidateUserAndGenerateJWToken", "GetAuthorizeTokenValidationForHub",
            "ConfigureHub", "ConfigureHubOption", "ConfigureHubForJWTRoute",
            "AuthAndGetJWTRoutePattern", "OnConnectedAsyncNext", "OnDisconnectedAsyncNext",
            "AuthenticateAndGenerateJwtTokenAsync", "IsUserConnected", "CleanupExpiredSessions"
        };

        return cls.Members
            .OfType<MethodDeclarationSyntax>()
            .Where(m =>
                m.Modifiers.Any(mod => mod.IsKind(SyntaxKind.PublicKeyword)) &&
                !m.AttributeLists.SelectMany(al => al.Attributes).Any(attr =>
                    attr.Name.ToString() == "G9AttrExcludeFromClientGeneration" ||
                    attr.Name.ToString() == "G9AttrExcludeFromClientGenerationAttribute" ||
                    attr.Name.ToString() == "G9AttrDenyAccess" ||
                    attr.Name.ToString() == "G9AttrDenyAccessAttribute") &&
                !excluded.Contains(m.Identifier.Text))
            .ToList();
    }

    private static string GenerateCode(
        string className,
        string clientInterface,
        List<MethodDeclarationSyntax> serverMethods,
        ClassDeclarationSyntax hubClass,
        List<(string Path, SyntaxTree Tree)> parsedTrees)
    {
        var methodsInterface = $"I{className}Methods";
        var listenersInterface = $"I{className}Listeners";
        var clientClass = $"{className}Client";

        // ReSharper disable once PossibleNullReferenceException
        var isJwtAuthHub = hubClass.BaseList!.Types.Any(bt => bt.ToString().Contains("G9AHubBaseWithJWTAuth"));
        var isSessionAndJwtAuthHub = hubClass.BaseList.Types.Any(bt => bt.ToString().Contains("G9AHubBaseWithSessionAndJWTAuth"));

        if (isJwtAuthHub || isSessionAndJwtAuthHub)
        {
            methodsInterface += "WithJWTAuth";
            listenersInterface += "WithJWTAuth";
            clientClass += "WithJWTAuth";
        }

        var routePattern = isJwtAuthHub || isSessionAndJwtAuthHub
            ? ExtractStringReturnValue(hubClass, "RoutePattern", "/SecureHub")
            : ExtractStringReturnValue(hubClass, "RoutePattern", "/" + className);
        var authRoutePattern = isJwtAuthHub || isSessionAndJwtAuthHub
            ? ExtractStringReturnValue(hubClass, "AuthAndGetJWTRoutePattern", "/AuthHub")
            : null;

        var listenerMethods = ResolveInterfaceMethods(clientInterface, parsedTrees);

        var listenersDef = GenerateListenersInterface(listenerMethods);
        var methodsDef = GenerateMethodsInterface(serverMethods);

        var serverProxyImpl = GenerateServerProxyImplementation(serverMethods);
        var listenerRegistration = GenerateListenerRegistration(listenerMethods);

        var baseClass = isJwtAuthHub || isSessionAndJwtAuthHub
            ? $"G9SignalRSuperNetCoreClientWithJWTAuth<{clientClass}, {methodsInterface}, {listenersInterface}>"
            : $"G9SignalRSuperNetCoreClient<{clientClass}, {methodsInterface}, {listenersInterface}>";

        string ctorParams, ctorBaseArgs;
        if (isJwtAuthHub || isSessionAndJwtAuthHub)
        {
            ctorParams =
                "string serverUrl, string? jwToken = null, " +
                "Func<IHubConnectionBuilder, IHubConnectionBuilder>? customConfigureBuilder = null, " +
                "Func<IHubConnectionBuilder, IHubConnectionBuilder>? customConfigureBuilderForAuthServer = null, " +
                "Action<HttpConnectionOptions>? configureHttpConnection = null, " +
                "Action<HttpConnectionOptions>? configureHttpConnectionForAuthServer = null";
            ctorBaseArgs =
                $"$\"{{serverUrl}}{routePattern}\", $\"{{serverUrl}}{authRoutePattern}\", jwToken, " +
                "customConfigureBuilder, customConfigureBuilderForAuthServer, " +
                "configureHttpConnection, configureHttpConnectionForAuthServer";
        }
        else
        {
            ctorParams =
                "string serverUrl, " +
                "Func<IHubConnectionBuilder, IHubConnectionBuilder>? customConfigureBuilder = null, " +
                "Action<HttpConnectionOptions>? configureHttpConnection = null";
            ctorBaseArgs = $"$\"{{serverUrl}}{routePattern}\", customConfigureBuilder, configureHttpConnection";
        }

        return $@"
/* ---------------------------------------------------------------
 *   Auto-generated AOT-safe client helper for hub '{className}'
 * --------------------------------------------------------------- */

/// <summary>Server methods callable from the client.</summary>
public interface {methodsInterface}
{{
{methodsDef}
}}

/// <summary>Client-side callbacks the server can invoke.</summary>
public interface {listenersInterface}
{{
{listenersDef}
}}

/// <summary>
/// Strongly-typed, AOT-safe client for the SignalR hub '{className}'.
/// </summary>
public partial class {clientClass} : {baseClass}, {listenersInterface}
{{
    private {className}ServerProxy? _serverProxy;

    public {clientClass}({ctorParams})
        : base({ctorBaseArgs})
    {{
    }}

    /// <inheritdoc />
    public override {methodsInterface} Server =>
        _serverProxy ??= new {className}ServerProxy(this);

    /// <inheritdoc />
    protected override void RegisterListenerMethods()
    {{
{listenerRegistration}
    }}

{GenerateDefaultListenerImplementations(listenerMethods)}
}}

/// <summary>
/// Hand-rolled (generated) typed proxy that invokes server methods through HubConnection
/// without any runtime reflection.
/// </summary>
internal sealed class {className}ServerProxy : {methodsInterface}
{{
    private readonly {clientClass} _owner;

    public {className}ServerProxy({clientClass} owner) {{ _owner = owner; }}

{serverProxyImpl}
}}";
    }

    private static List<(string Name, string ReturnType, List<(string Type, string Name)> Params, string XmlComment)>
        ResolveInterfaceMethods(string interfaceName, List<(string Path, SyntaxTree Tree)> parsedTrees)
    {
        var result = new List<(string, string, List<(string, string)>, string)>();

        var iface = parsedTrees
            .SelectMany(t => t.Tree.GetRoot().DescendantNodes().OfType<InterfaceDeclarationSyntax>())
            .FirstOrDefault(i => i.Identifier.Text == interfaceName);

        if (iface == null) return result;

        foreach (var m in iface.Members.OfType<MethodDeclarationSyntax>())
        {
            var ps = m.ParameterList.Parameters
                .Select(p => (p.Type?.ToString() ?? "object", p.Identifier.Text))
                .ToList();
            result.Add((m.Identifier.Text, m.ReturnType.ToString(), ps, ExtractXmlComment(m)));
        }

        return result;
    }

    private static string GenerateListenersInterface(
        List<(string Name, string ReturnType, List<(string Type, string Name)> Params, string XmlComment)> methods)
    {
        var sb = new StringBuilder();
        foreach (var (name, ret, ps, comment) in methods)
        {
            if (!string.IsNullOrWhiteSpace(comment)) sb.Append(comment);
            var paramList = string.Join(", ", ps.Select(p => $"{p.Type} {p.Name}"));
            sb.AppendLine($"    {ret} {name}({paramList});");
        }
        return sb.ToString();
    }

    private static string GenerateMethodsInterface(List<MethodDeclarationSyntax> methods)
    {
        var sb = new StringBuilder();
        foreach (var m in methods)
        {
            var comment = ExtractXmlComment(m);
            if (!string.IsNullOrWhiteSpace(comment)) sb.Append(comment);
            var ret = m.ReturnType.ToString();
            var ps = string.Join(", ", m.ParameterList.Parameters.Select(p => $"{p.Type} {p.Identifier}"));
            sb.AppendLine($"    {ret} {m.Identifier}({ps});");
        }
        return sb.ToString();
    }

    private static string GenerateServerProxyImplementation(List<MethodDeclarationSyntax> methods)
    {
        var sb = new StringBuilder();
        foreach (var m in methods)
        {
            var name = m.Identifier.Text;
            var ret = m.ReturnType.ToString();
            var ps = m.ParameterList.Parameters;
            var paramList = string.Join(", ", ps.Select(p => $"{p.Type} {p.Identifier}"));
            var argArray = ps.Count == 0
                ? "global::System.Array.Empty<object?>()"
                : "new object?[] { " + string.Join(", ", ps.Select(p => p.Identifier.ToString())) + " }";

            // Detect Task vs Task<T>
            if (ret == "Task" || ret == "System.Threading.Tasks.Task")
            {
                sb.AppendLine($@"    public {ret} {name}({paramList})
        => _owner.Connection.SendCoreAsync(""{name}"", {argArray});");
            }
            else if (ret.StartsWith("Task<") || ret.StartsWith("System.Threading.Tasks.Task<"))
            {
                var inner = ret.Substring(ret.IndexOf('<') + 1, ret.LastIndexOf('>') - ret.IndexOf('<') - 1);
                sb.AppendLine($@"    public {ret} {name}({paramList})
        => _owner.Connection.InvokeCoreAsync<{inner}>(""{name}"", {argArray});");
            }
            else
            {
                sb.AppendLine($@"    public {ret} {name}({paramList})
        => throw new global::System.NotSupportedException(""Unsupported return type for hub method '{name}': {ret}. Use Task or Task<T>."");");
            }
        }
        return sb.ToString();
    }

    private static string GenerateListenerRegistration(
        List<(string Name, string ReturnType, List<(string Type, string Name)> Params, string XmlComment)> methods)
    {
        var sb = new StringBuilder();
        foreach (var (name, _, ps, _) in methods)
        {
            if (ps.Count == 0)
            {
                sb.AppendLine($"        Connection.On(\"{name}\", () => {name}());");
            }
            else
            {
                var generics = string.Join(", ", ps.Select(p => p.Type));
                var paramDecl = string.Join(", ", ps.Select((p, i) => $"{p.Type} a{i}"));
                var paramUse = string.Join(", ", ps.Select((_, i) => $"a{i}"));
                sb.AppendLine($"        Connection.On<{generics}>(\"{name}\", ({paramDecl}) => {name}({paramUse}));");
            }
        }
        return sb.ToString();
    }

    private static string GenerateDefaultListenerImplementations(
        List<(string Name, string ReturnType, List<(string Type, string Name)> Params, string XmlComment)> methods)
    {
        var sb = new StringBuilder();
        foreach (var (name, ret, ps, _) in methods)
        {
            var paramList = string.Join(", ", ps.Select(p => $"{p.Type} {p.Name}"));
            sb.AppendLine($@"    public virtual {ret} {name}({paramList}) => global::System.Threading.Tasks.Task.CompletedTask;");
        }
        return sb.ToString();
    }

    private static string ExtractXmlComment(MethodDeclarationSyntax method)
    {
        var trivia = method.GetLeadingTrivia()
            .Select(t => t.GetStructure())
            .OfType<DocumentationCommentTriviaSyntax>()
            .FirstOrDefault();

        if (trivia == null) return string.Empty;

        var sb = new StringBuilder();
        foreach (var node in trivia.Content.OfType<XmlElementSyntax>())
        {
            var elementName = node.StartTag.Name.ToString();
            if (elementName == "param")
            {
                var paramName = node.StartTag.Attributes.OfType<XmlNameAttributeSyntax>()
                    .FirstOrDefault()?.Identifier.ToString();
                var paramContent = string.Join(" ", node.Content.OfType<XmlTextSyntax>()
                    .SelectMany(t => t.TextTokens).Select(t => t.Text.Trim())
                    .Where(t => !string.IsNullOrEmpty(t)));
                sb.AppendLine($"    /// <param name=\"{paramName}\">{paramContent}</param>");
            }
            else
            {
                sb.AppendLine($"    /// <{elementName}>");
                foreach (var content in node.Content.OfType<XmlTextSyntax>())
                {
                    var text = string.Join(" ", content.TextTokens.Select(t => t.Text.Trim())
                        .Where(t => !string.IsNullOrEmpty(t)));
                    sb.AppendLine($"    /// {text}");
                }
                sb.AppendLine($"    /// </{elementName}>");
            }
        }
        return sb.ToString();
    }

    private static string ExtractStringReturnValue(ClassDeclarationSyntax hubClass, string methodName, string fallback)
    {
        var method = hubClass.Members.OfType<MethodDeclarationSyntax>()
            .FirstOrDefault(m => m.Identifier.Text == methodName && m.ParameterList.Parameters.Count == 0);

        if (method == null) return fallback;

        // method body: return "x";  OR  expression body: => "x";
        if (method.Body != null)
        {
            var ret = method.Body.Statements.OfType<ReturnStatementSyntax>().FirstOrDefault();
            if (ret?.Expression is LiteralExpressionSyntax lit && lit.IsKind(SyntaxKind.StringLiteralExpression))
                return lit.Token.ValueText;
        }
        else if (method.ExpressionBody?.Expression is LiteralExpressionSyntax expLit
                 && expLit.IsKind(SyntaxKind.StringLiteralExpression))
        {
            return expLit.Token.ValueText;
        }

        return fallback;
    }
}
